config/routes.rb
Rails.application.routes.draw do
  get 'sales', to: 'sales#done'
  get 'sales/new'
  post 'sales', to: 'sales#create'
  get 'sales/:id', to: 'sales#show', as: 'sale'
  delete 'sales/:id', to: 'sales#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sale.rb
class Sale < ApplicationRecord
  validates :cod, uniqueness: true
  validates :detail, presence: true
  validates :category, inclusion: { in: %w(uno dos tres cuatro cinco), message: "%{value} is not a valid size" }
  validates :value, numericality: true
  validates_inclusion_of :discount, :in => 1..40
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  def done
    @sales = Sale.all
  end

  def new
    @sale = Sale.new
  end

  def create
    @sale = Sale.new(sale_params)
    if @sale.tax == 1
      @sale.total = (1.19)*(@sale.value - @sale.value*@sale.discount/100)
    else
      @sale.total = @sale.value - @sale.value*@sale.discount/100
    end
    @sale.save
    redirect_to sales_path
    flash[:notice] = 'El registro fue almacenado con éxito!'
  end

  def show
    @sale = Sale.find(params[:id])
  end

  def destroy
    @sale = Sale.find(params[:id])
    @sale.destroy
    redirect_to sales_path
  end

  private
  def sale_params
    params.require(:sale).permit(:cod, :category, :detail, :value, :discount, :tax, :total)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Proyecto</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/sales/done.html.erb
<center>
  <br>
  <h1>Todas las ventas</h1>
  <br>
</center>
<p id="notice"><%= notice %></p>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Codigo</th>
        <th scope="col">Categoria</th>
        <th scope="col">Total</th>
        <th scope="col">Opciones</th>
      </tr>
    </thead>
    <tbody>
      <% k = 0%>
      <%= @sales.each do |sale| %>
      <% k = k + 1 %>
      <tr>
        <th scope="row"><%= k %></th>
        <td><%= sale.cod %></td>
        <td><%= sale.category %></td>
        <td><%= sale.total %></td>
        <td><%= link_to 'ver', sale %>
            <%= link_to 'Borrar', sale, method: :delete %></td>
      </tr>
      <% end %>
    </tbody>
  </table>

  <%= link_to 'Nueva venta', sales_new_path, class: 'btn btn-lg btn-primary' %>

app/views/sales/new.html.erb
<center>
  <br>
<h1>Ingresar venta</h1>
  <br>
</center>

  <div class="row justify-content-md-center">
    <div class="col-md-12">
      <div class="row justify-content-md-center">
        <%= form_with model: @sale, local: true do |f| %>
        <div class="form-group col-md-12">
          <%= f.label :cod, "Código" %>
          <%= f.text_field :cod, class: 'form-control'%>
        </div>
        <div class="form-group col-md-12">
          <%= f. label :category%>
          <%= f.text_field :category, class: 'form-control'%>
        </div>
        <div class="form-group col-md-12">
          <%= f. label :detail, "Detalle" %>
          <%= f.text_area :detail, class: 'form-control'%>
        </div>
        <div class="form-group col-md-12">
          <%= f. label :value, "Valor" %>
          <%= f.text_field :value, class: 'form-control'%>
        </div>
        <div class="form-group col-md-12">
          <%= f. label :discount, "% Descuento" %>
          <%= f.text_field :discount, class: 'form-control' %>
        </div>
        <div class="form-group col-md-6">
          <%= f. label :tax, "Con IVA" %>
          <%= f.check_box :tax %>
          <%= f.submit "Crear", class: 'btn btn-lg btn-primary' %>

        </div>
        <div class="form-group col-md-6">
          <%= link_to 'Volver', sales_path, class: 'btn btn-lg btn-success' %>
        </div>
        <% end %>

      </div>
    </div>
  </div>

app/views/sales/show.html.erb
<center>
  <br>
  <h1>Código venta: <%= @sale.cod %></h1>
  <br>
</center>
<div class="row justify-content-md-center">
  <div class="col-md-6">
    <div class="row">
    </div>
      <table class="table">
        <tbody>
          <tr>
            <th scope="row">Categoria</th>
            <td><%= @sale.category %></td>
          </tr>
          <tr>
            <th scope="row">Detalle</th>
            <td><%= @sale.detail %></td>
          </tr>
          <tr>
            <th scope="row">Valor</th>
            <td><%= @sale.value %></td>
          </tr>
          <tr>
            <th scope="row">Descuento</th>
            <td><%= @sale.discount %></td>
          </tr>
          <tr>
            <th scope="row">Impuesto</th>
            <td><%= @sale.tax %></td>
          </tr>
          <tr>
            <th scope="row">Total</th>
            <td><%= @sale.total %></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
    <%= link_to 'Volver', sales_path, class: 'btn btn-lg btn-primary' %>